# Generated by Django 4.2.1 on 2023-05-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="comment_user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_user",
        ),
    ]
