# Generated by Django 4.2.1 on 2023-05-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_comment_comment_user_remove_post_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="username",
            field=models.CharField(default="anonymous", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="username",
            field=models.CharField(default="anonymous", max_length=50),
        ),
    ]
